trade/jsontypes/types.go
trade/types.go

add NetAssets, InitMargin, MaintenanceMargin on TradeContext's AccountBalance. See details on https://open.longbridgeapp.com/en/docs/log_change

add NetAssets, InitMargin, MaintenanceMargin on accountbalance

---

examples/subscribe_quote/main.go
quote/context.go
quote/core.go
quote/store.go
quote/types.go

Use depth, quote, trade, brokers even callback instead of one callback function

Use four quote callback instead of one callback

---

trade/core.go

trade context push event use jsontypes

---

go.mod
go.sum

Detail see https://github.com/longbridgeapp/openapi-protocol/pull/3

update longbridge protocol return res LBError

---

quote/context.go
quote/jsontypes/types.go
quote/types.go

Adding WatchedGroup function.
See API doc on https://open.longbridgeapp.com/en/docs/quote/individual/watchlist_groups

add WatchedGroup

---

trade/context.go
trade/jsontypes/types.go
trade/types.go

CashFlows ,FundPositions and StockPositions should use jsontypes to accept api result

fix CashFlows ,FundPositions and StockPositions no return

---

trade/context.go
trade/jsontypes/types.go
trade/types.go

Add margin ratio api.
Reference:  https://open.longbridgeapp.com/docs/trade/asset/margin_ratio

add MarginRatio Interface

---

quote/core.go

Fixing quote context's broker and trade events is empty

fix quote context's broker and trade event

---

internal/util/numutil.go
quote/context.go
quote/core.go
quote/types.go

add CalcIndex interface.
Reference: https://open.longbridgeapp.com/en/docs/quote/pull/calc-index

add CalcIndex interface

---

quote/core.go
quote/options.go

switch quote to v2

---

quote/context.go
quote/core.go

Quote.OptionChainInfoByDate set wrong command parameter, and response unmarshal  incorrect .

fix quote.OptionChainInfoByDate

---

README.md
config/config.go
go.mod
go.sum
log/logger.go
longbridge/options.go
quote/context.go
quote/core.go
quote/options.go
trade/context.go
trade/core.go
trade/options.go

Add some LongBridge Protocol options, user can configure longbridge client

add some LongBridge Protocol options

---

http/encrypt.go
http/encrypt_test.go
http/signature.go

- add EncryptPassword to encrypt password
- signature should not override `x-timestamp` if exists

Encrypt helper

---

README.md
config/config.go

- support `LONGPORT_` prefix env
- support set region

support LONGPORT_ prefix and support set region

---

.gitignore
README.md
examples/get_quote/main.go
examples/submit_order/main.go
go.mod
go.sum
quote/context.go
quote/core.go
quote/types.go

https://open.longportapp.com/en/docs/quote/pull/warrant-filter

Warrant filter

---

trade/request_values.go

修复 FundPositions 和 StockPositions 查询参数不生效的问题

fix FundPositions and StockPositions params

---

quote/context.go
quote/jsontypes/types.go
quote/types.go

add `QuoteContext.SecurityList` to list all securities

add QuoteContext.SecurityList to list all securities

---

http/client.go
http/errors.go
quote/context.go
quote/jsontypes/types.go
quote/types.go

`CraeteWatchlistGroup` - create a new watchlist group
`DeleteWatchlistGroup` - delete a watchlist group
`UpdateWatchlistGroup` - update a watchlist group

add Watchlist operations

---

config/config.go
examples/get_quote/main.go
examples/go.mod
examples/go.sum
examples/submit_order/main.go

Changes
- optimize appkey, appsecret, apptoken required message, replace LONGBRIDGE by LONGPORT
- optimize example codes

optimize example codes

---

trade/jsontypes/types.go
trade/types.go

add missing field Remark

---

trade/context.go

openapi-sdk 撤销订单接口是 CancelOrder。 Go 也添加 CancelOrder。

feat: CancelOrder function

---

README.md
config/config.go
config/config_test.go
config/config_toml.go
config/config_yaml.go

修复通过 toml 或者 yaml 文件配置。
Fixes #52

fix toml yaml config

---

internal/util/copyutil.go
internal/util/copyutil_test.go

Fix EstimateMaxPurchaseQuantity not return value

---

quote/core.go

修复查询 OptionQuote 接口无法返回期权数据，并且不会返回错误

fix option quote command

---

quote/core.go
quote/options.go
trade/core.go
trade/options.go

trade/quote add OnReconnect Option to register reconnect callbacks

feat: trade/quote add OnReconnect Option to register reconnect callbacks

---

http/client.go
http/options.go
quote/context.go
trade/context.go

Add accept-language when do http request

fix: should set accept-language by config.Language
